[package]
name = "flux-cli"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
thiserror.workspace = true
toml = "0.8"
