[package]
name = "flux-core"
version.workspace = true
edition.workspace = true

[dependencies]
flux-abi = { path = "../abi" }

alloy.workspace = true
thiserror.workspace = true
async-trait = "0.1.89"
futures = "0.3.31"